core = "7.x"
api = "2"

projects[devel][subdir] = "contrib"
projects[object_log][subdir] = "contrib"
projects[maillog][subdir] = "contrib"
projects[field_tools][subdir] = "contrib"
projects[diff][subdir] = "contrib"
projects[architecture][subdir] = "contrib"
projects[which_feature][subdir] = "contrib"
projects[admin_menu][subdir] = "contrib"
projects[view_mode_displays][subdir] = "contrib"
projects[field_info][subdir] = "contrib"
